version: "3.8"
services:
  nginx:
    build: ./client
    ports: 
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - backend
  backend:
    build: ./server
    ports:
      - "4040:4040"
